import { useCallback,useEffect,useMemo,useState } from 'react';
import { Plus, Search, SlidersHorizontal, RefreshCw, Ticket, Clock3, CheckCircle2, CircleDot, XCircle, ChevronLeft, ChevronRight } from 'lucide-react';
import Modal from './components/Modal'; import TicketForm from './components/TicketForm'; import TicketDetail from './components/TicketDetail'; import { api } from './services/api';

const STATUSES=['Open','In Progress','Resolved','Closed']; const PRIORITIES=['Low','Medium','High'];
const fmt=d=>new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
function Stat({icon:Icon,label,value,kind}){return <div className="stat-card"><div className={`stat-icon ${kind}`}><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Badge({type,value}){return <span className={`pill ${type}-${value.toLowerCase().replaceAll(' ','-')}`}>{value}</span>}

export default function App(){
 const [tickets,setTickets]=useState([]),[meta,setMeta]=useState({total:0,page:1,totalPages:1}),[customers,setCustomers]=useState([]);
 const [filters,setFilters]=useState({search:'',status:'',priority:'',customer:'',sortBy:'createdAt',sortOrder:'desc',page:1,limit:8});
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[detail,setDetail]=useState(null),[editing,setEditing]=useState(null),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await api.listTickets(filters);setTickets(data.rows);setMeta(data)}catch(e){setError(e.message)}finally{setLoading(false)}},[filters]);
 useEffect(()=>{load()},[load]); useEffect(()=>{api.customers().then(setCustomers).catch(()=>{})},[tickets.length]);
 const counts=useMemo(()=>({open:tickets.filter(t=>t.status==='Open').length,inProgress:tickets.filter(t=>t.status==='In Progress').length,resolved:tickets.filter(t=>t.status==='Resolved').length,closed:tickets.filter(t=>t.status==='Closed').length}),[tickets]);
 const setFilter=(name,value)=>setFilters(f=>({...f,[name]:value,page:1}));
 const save=async data=>{setSaving(true);try{if(editing)await api.updateTicket(editing.id,data);else await api.createTicket(data);setCreating(false);setEditing(null);await load();}catch(e){throw e}finally{setSaving(false)}};
 const afterDelete=()=>{setDetail(null);load()};
 return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark"><Ticket size={22}/></div><div><strong>ServiceDesk</strong><span>Ticket management</span></div></div><button className="btn primary" onClick={()=>setCreating(true)}><Plus size={18}/> New ticket</button></header>
 <main className="content"><div className="page-heading"><div><p className="eyebrow">Operations dashboard</p><h1>Service tickets</h1><p>Track customer requests from open to resolution.</p></div><button className="icon-btn refresh" onClick={load} title="Refresh"><RefreshCw size={19}/></button></div>
 <div className="stats"><Stat icon={CircleDot} label="Open" value={counts.open} kind="open"/><Stat icon={Clock3} label="In progress" value={counts.inProgress} kind="progress"/><Stat icon={CheckCircle2} label="Resolved" value={counts.resolved} kind="resolved"/><Stat icon={XCircle} label="Closed" value={counts.closed} kind="closed"/></div>
 <section className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input value={filters.search} onChange={e=>setFilter('search',e.target.value)} placeholder="Search title or customer…"/></div><div className="filters"><select value={filters.status} onChange={e=>setFilter('status',e.target.value)}><option value="">All statuses</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select><select value={filters.priority} onChange={e=>setFilter('priority',e.target.value)}><option value="">All priorities</option>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select><select value={filters.customer} onChange={e=>setFilter('customer',e.target.value)}><option value="">All customers</option>{customers.map(x=><option key={x}>{x}</option>)}</select><select value={`${filters.sortBy}:${filters.sortOrder}`} onChange={e=>{const [sortBy,sortOrder]=e.target.value.split(':');setFilters(f=>({...f,sortBy,sortOrder,page:1}))}}><option value="createdAt:desc">Newest first</option><option value="createdAt:asc">Oldest first</option><option value="priority:desc">High priority first</option><option value="priority:asc">Low priority first</option></select></div></div>
 {error&&<div className="alert">{error}<button onClick={load}>Retry</button></div>}
 {loading?<div className="center-state"><RefreshCw className="spin" size={24}/>Loading tickets…</div>:tickets.length===0?<div className="empty"><SlidersHorizontal size={32}/><h3>No tickets found</h3><p>Try changing the filters or create a new ticket.</p></div>:<div className="table-wrap"><table><thead><tr><th>ID</th><th>Customer</th><th>Ticket</th><th>Priority</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{tickets.map(t=><tr key={t.id} onClick={()=>setDetail(t.id)}><td><span className="ticket-id">#{String(t.id).padStart(4,'0')}</span></td><td><strong>{t.customerName}</strong></td><td><div className="ticket-title">{t.title}</div><div className="ticket-desc">{t.description}</div></td><td><Badge type="priority" value={t.priority}/></td><td><Badge type="status" value={t.status}/></td><td>{fmt(t.createdAt)}</td><td><button className="view-btn" onClick={e=>{e.stopPropagation();setDetail(t.id)}}>View</button></td></tr>)}</tbody></table></div>}
 {meta.total>0&&<div className="pagination"><span>Showing <strong>{Math.min((meta.page-1)*meta.limit+1,meta.total)}–{Math.min(meta.page*meta.limit,meta.total)}</strong> of <strong>{meta.total}</strong></span><div><button className="page-btn" disabled={meta.page<=1} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}><ChevronLeft size={16}/></button><span className="page-number">{meta.page} / {meta.totalPages}</span><button className="page-btn" disabled={meta.page>=meta.totalPages} onClick={()=>setFilters(f=>({...f,page:f.page+1}))}><ChevronRight size={16}/></button></div></div>}
 </section></main>
 {creating&&<Modal title="Create a new ticket" onClose={()=>setCreating(false)}><TicketForm onSubmit={save} onCancel={()=>setCreating(false)} loading={saving}/></Modal>}
 {editing&&<Modal title={`Edit ticket #${editing.id}`} onClose={()=>setEditing(null)}><TicketForm ticket={editing} onSubmit={save} onCancel={()=>setEditing(null)} loading={saving}/></Modal>}
 {detail&&<TicketDetail id={detail} onClose={()=>setDetail(null)} onDeleted={afterDelete} onEdit={ticket=>{setDetail(null);setEditing(ticket)}}/>}
 </div>
}
