import { Router } from 'express';
import { createTicket, deleteTicket, getCustomers, getTicket, getTickets, updateTicket } from '../controllers/ticketController.js';
const router = Router();
router.get('/customers', getCustomers);
router.get('/', getTickets);
router.get('/:id', getTicket);
router.post('/', createTicket);
router.put('/:id', updateTicket);
router.delete('/:id', deleteTicket);
export default router;
